### ISSUE TITLE
Optimise XPath queries

### ISSUE THREAD

**Issue by danni** [bbangert/lettuce_webdriver#35]
There's quite a few queries in LWD which do things like:

        text_field = find_field(world.browser, 'text', field_name) or \
            find_field(world.browser, 'textarea', field_name) or \
            find_field(world.browser, 'password', field_name) or \
            ...

Each one of these triggers a single XPath query to the WebDriver, which if you're using a network webdriver, such as BrowserStack, is another round-trip across the Internet.

Need to combine these into single queries to the WebDriver.

**Comment by koterpillar** [comment]
This has been fixed in #42.

**Comment by miratcan** [comment]
@koterpillar Why fixed issues are remaining open?

**Comment by koterpillar** [comment]
@miratcan I am not the maintainer for this repository and cannot close it.
